version: "3.8"
services:
  redis:
      image: 'redis:latest'
      ports:
        - '6379:6379'
  google_calendar_integration:
    build:
      context: ./
      dockerfile: Dockerfile.local
    container_name: google_calendar_integration
    env_file:
      - .env
    privileged: true

    volumes:
      - /dev/shm:/dev/shm
      - ./:/app
    ports:
      - "8080:8080"

    depends_on:
      - redis

    command: ["sh", "./docker-entrypoint-dev.sh"]

volumes:
  psql: null
